export const FETCH_COMPANY_RENTAL_EMPLOYEE = "FETCH_COMPANY_RENTAL_EMPLOYEE";
export const FETCH_COMPANY_RENTAL_RENT_EMPLOYEE = "FETCH_COMPANY_RENTAL_RENT_EMPLOYEE";
export const FETCH_PAYMENTS_NOTES = "FETCH_PAYMENTS_NOTES";
