// Accounting Types
export const FETCH_COMPANY_ACCOUNTING = 'FETCH_COMPANY_ACCOUNTING'

// Rentals Types
export const ADD_COMPANY_RENTAL = 'ADD_COMPANY_RENTAL'
export const FETCH_COMPANY_RENTALS = 'FETCH_COMPANY_RENTALS'