// Accounting Types
export const FETCH_COMPANY_ACCOUNTING = "FETCH_COMPANY_ACCOUNTING";

// Rentals Types
export const FETCH_COMPANY_RENTAL = "FETCH_COMPANY_RENTAL";
export const FETCH_COMPANY_RENTALS = "FETCH_COMPANY_RENTALS";

// Rent Types
export const FETCH_RENT_INFO = "FETCH_RENT_INFO";

// Employees Types

export const FETCH_COMPANY_EMPLOYEES = "FETCH_COMPANY_EMPLOYEES";
export const FETCH_COMPANY_EMPLOYEE = "FETCH_COMPANY_EMPLOYEE";
